### ISSUE TITLE
define thunk behavior with polymer 2.0 classes

### ISSUE THREAD

**Issue by togonow** [Polymer/polycasts#18]
How to define a redux thunk that can be mixed in (used to be in the behavior array) with the new polylmer 2.0 elements.

**Comment by togonow** [comment]
the example in the documentation uses thunk within the element as below. i'm  trying to separate the logic from the polymer element
`class DemoApp extends ReduxMixin(Polymer.Element) {
  // ...

  connectedCallback() {
    super.connectedCallback();

    // Update message using Redux Thunk
    this.dispatch((dispatch) => {
      dispatch('updateMessage', 'Please wait...');

      // Do async task
      setTimeout(() => {
        dispatch('updateMessage', 'Sorry for being late!');
      }, 1000);
    });
  }
}`

**Comment by johnthad** [comment]
See my update to Polycast 62 for how I did it: https://github.com/johnthad/polycast62
and read this excellent [post on mixins](http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/) by Justin Fagini.

(My Polycast 61 is here https://github.com/johnthad/polycast62)

**Comment by togonow** [comment]
Thank you soo much

**Comment by zmeireles** [comment]
Awesome!
