### ISSUE TITLE
'ep06-simple-app' app not working properly on mobile chrome, but working nicely on mobile Safari, both case are on iphone 5.

### ISSUE THREAD

**Issue by Simon-Li** [Polymer/polycasts#3]
@robdodson , looks the core-drawer-toggle not function properly, any clues? BTW, 'ep05-core-drawer-panel' app works fine on mobile chrome. thanks!

**Comment by robdodson** [comment]
Hm... I don't have an iphone to test but my teammate said it worked fine on his iPhone 6 with a slightly out of date beta of Chrome. I'll try to test on some more devices

**Comment by arthurvr** [comment]
Tends to work fine for me on an iPhone 5, latest IOS 8.

@robdodson you don't need an iPhone to test things, by the way. Xcode's simulator works fine in most cases.

**Comment by robdodson** [comment]
Closing this. Happy to reopen if anyone else has issues.
